project_name: aws-ebs-state-exporter
release:
  github:
    owner: tufitko
    name: aws-ebs-state-exporter

builds:
  - id: aws-ebs-state-exporter
    binary: exporter
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - aws-ebs-state-exporter
    image_templates:
      - "tufitko/aws-ebs-state-exporter:v{{ .Version }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
    use: buildx
  - goos: linux
    goarch: arm64
    ids:
      - aws-ebs-state-exporter
    image_templates:
      - "tufitko/aws-ebs-state-exporter:v{{ .Version }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
    use: buildx
docker_manifests:
  - name_template: tufitko/aws-ebs-state-exporter:v{{ .Version }}
    image_templates:
      - tufitko/aws-ebs-state-exporter:v{{ .Version }}-amd64
      - tufitko/aws-ebs-state-exporter:v{{ .Version }}-arm64
